# Generated by Django 5.2.4 on 2025-11-14 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nombre del documento', max_length=300)),
                ('file', models.FileField(help_text='Archivo PDF o documento', upload_to='rag_documents/')),
                ('file_type', models.CharField(default='pdf', max_length=50)),
                ('page_count', models.IntegerField(default=0, help_text='Número de páginas')),
                ('chunk_count', models.IntegerField(default=0, help_text='Número de fragmentos indexados')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('indexed', 'Indexado'), ('error', 'Error')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Colección de Documentos',
                'verbose_name_plural': 'Colecciones de Documentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RAGQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(help_text='Pregunta del usuario')),
                ('response', models.TextField(help_text='Respuesta generada')),
                ('chunks_used', models.JSONField(default=list, help_text='IDs de chunks usados para la respuesta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rag_chat.documentcollection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rag_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consulta RAG',
                'verbose_name_plural': 'Consultas RAG',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField(help_text='Índice del fragmento')),
                ('content', models.TextField(help_text='Texto del fragmento')),
                ('embedding', models.JSONField(default=list, help_text='Vector embedding (lista de floats)')),
                ('metadata', models.JSONField(default=dict, help_text='Metadatos: página, sección, enlace, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='rag_chat.documentcollection')),
            ],
            options={
                'verbose_name': 'Fragmento de Documento',
                'verbose_name_plural': 'Fragmentos de Documentos',
                'ordering': ['collection', 'chunk_index'],
                'indexes': [models.Index(fields=['collection', 'chunk_index'], name='rag_chat_do_collect_10f051_idx')],
            },
        ),
    ]
