# Generated by Django 5.2.4 on 2025-09-16 12:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('vacaciones', 'Vacaciones'), ('permiso', 'Permiso'), ('suspendido', 'Suspendido')], default='activo', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="El número debe estar en formato: '+999999999'", regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_contrato',
            field=models.CharField(choices=[('tiempo_completo', 'Tiempo Completo'), ('medio_tiempo', 'Medio Tiempo'), ('temporal', 'Temporal'), ('por_proyecto', 'Por Proyecto')], default='tiempo_completo', max_length=20, verbose_name='Tipo de contrato'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cargo',
            field=models.CharField(max_length=100, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_contratacion',
            field=models.DateField(verbose_name='Fecha de contratación'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='salario',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario base'),
        ),
        migrations.CreateModel(
            name='Bonificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('recurrente', models.BooleanField(default=False, verbose_name='¿Es recurrente?')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de finalización (opcional)')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonificaciones', to='nominas.empleado', verbose_name='Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de pago')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('tipo', models.CharField(choices=[('salario', 'Salario'), ('bono', 'Bonificación'), ('vacaciones', 'Pago Vacaciones'), ('liquidacion', 'Liquidación'), ('otro', 'Otro')], default='salario', max_length=20, verbose_name='Tipo de pago')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='nominas/comprobantes/', verbose_name='Comprobante')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='nominas.empleado', verbose_name='Empleado')),
            ],
        ),
    ]
