# Generated by Django 5.2.4 on 2025-10-27 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nominas", "0002_empleado_direccion_empleado_email_empleado_estado_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="empleado",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="empleado",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario del sistema",
            ),
        ),
    ]
