# Generated by Django 5.2.4 on 2026-02-18 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarouselImage',
        ),
        migrations.DeleteModel(
            name='SiteImage',
        ),
        migrations.DeleteModel(
            name='SiteImageSection',
        ),
    ]
