# Generated by Django 5.2.3 on 2025-08-25 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_perfilusuario_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='cliente_desde',
        ),
    ]
