# Generated by Django 5.2.4 on 2025-12-11 23:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_perfilusuario_cliente_desde'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CambioPasswordAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('motivo', models.TextField(blank=True)),
                ('administrador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_password_realizados', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_password', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría de Cambio de Contraseña',
                'verbose_name_plural': 'Auditorías de Cambios de Contraseña',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
