# Generated by Django 5.2.4 on 2026-02-18 13:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('image', models.ImageField(upload_to='carousel/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Imagen')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Texto alternativo')),
                ('caption', models.CharField(blank=True, max_length=300, verbose_name='Texto descriptivo')),
                ('link_url', models.URLField(blank=True, verbose_name='URL de enlace')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('width', models.IntegerField(blank=True, editable=False, null=True)),
                ('height', models.IntegerField(blank=True, editable=False, null=True)),
                ('file_size', models.IntegerField(blank=True, editable=False, null=True, verbose_name='Tamaño de archivo (bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Imagen del Carrusel',
                'verbose_name_plural': 'Imágenes del Carrusel',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteImageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la sección')),
                ('section_type', models.CharField(choices=[('hero_carousel', 'Carrusel Principal'), ('about', 'Sección Acerca de'), ('services', 'Servicios'), ('header', 'Encabezado'), ('footer', 'Pie de Página'), ('banner', 'Banner'), ('icon', 'Icono'), ('background', 'Fondo'), ('custom', 'Personalizado')], max_length=50, verbose_name='Tipo de sección')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sección de Imagen',
                'verbose_name_plural': 'Secciones de Imágenes',
                'ordering': ['section_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('image', models.ImageField(upload_to='site_images/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Imagen')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Texto alternativo')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('width', models.IntegerField(blank=True, editable=False, null=True)),
                ('height', models.IntegerField(blank=True, editable=False, null=True)),
                ('file_size', models.IntegerField(blank=True, editable=False, null=True, verbose_name='Tamaño de archivo (bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='site_images.siteimagesection', verbose_name='Sección')),
            ],
            options={
                'verbose_name': 'Imagen del Sitio',
                'verbose_name_plural': 'Imágenes del Sitio',
                'ordering': ['section', 'order', '-created_at'],
            },
        ),
    ]
