# Generated by Django 5.2.4 on 2026-02-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('hero', 'Sección Hero (Portada)'), ('about', 'Sección Acerca de'), ('cocktails', 'Sección Cócteles'), ('services', 'Sección Servicios'), ('reservations', 'Sección Reservas')], max_length=50, unique=True, verbose_name='Sección')),
                ('hero_title', models.CharField(blank=True, max_length=200, verbose_name='Título principal')),
                ('hero_subtitle', models.TextField(blank=True, verbose_name='Subtítulo / Descripción')),
                ('hero_button1_text', models.CharField(blank=True, max_length=100, verbose_name='Texto botón 1')),
                ('hero_button2_text', models.CharField(blank=True, max_length=100, verbose_name='Texto botón 2')),
                ('about_title', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('about_paragraph1', models.TextField(blank=True, verbose_name='Párrafo 1')),
                ('about_paragraph2', models.TextField(blank=True, verbose_name='Párrafo 2')),
                ('about_paragraph3', models.TextField(blank=True, verbose_name='Párrafo 3')),
                ('cocktails_title', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('cocktails_subtitle', models.TextField(blank=True, verbose_name='Subtítulo')),
                ('services_title', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('services_subtitle', models.TextField(blank=True, verbose_name='Subtítulo')),
                ('service1_number', models.CharField(blank=True, max_length=20, verbose_name='Estadística 1 (número)')),
                ('service1_title', models.CharField(blank=True, max_length=100, verbose_name='Estadística 1 (título)')),
                ('service1_description', models.TextField(blank=True, verbose_name='Estadística 1 (descripción)')),
                ('service2_number', models.CharField(blank=True, max_length=20, verbose_name='Estadística 2 (número)')),
                ('service2_title', models.CharField(blank=True, max_length=100, verbose_name='Estadística 2 (título)')),
                ('service2_description', models.TextField(blank=True, verbose_name='Estadística 2 (descripción)')),
                ('service3_number', models.CharField(blank=True, max_length=20, verbose_name='Estadística 3 (número)')),
                ('service3_title', models.CharField(blank=True, max_length=100, verbose_name='Estadística 3 (título)')),
                ('service3_description', models.TextField(blank=True, verbose_name='Estadística 3 (descripción)')),
                ('service4_number', models.CharField(blank=True, max_length=20, verbose_name='Estadística 4 (número)')),
                ('service4_title', models.CharField(blank=True, max_length=100, verbose_name='Estadística 4 (título)')),
                ('service4_description', models.TextField(blank=True, verbose_name='Estadística 4 (descripción)')),
                ('reservations_title', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('reservations_text', models.TextField(blank=True, verbose_name='Texto descriptivo')),
                ('reservations_whatsapp', models.CharField(blank=True, max_length=30, verbose_name='Número de WhatsApp')),
                ('reservations_button_text', models.CharField(blank=True, default='Reservar por WhatsApp', max_length=100, verbose_name='Texto del botón')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contenido del Sitio',
                'verbose_name_plural': 'Contenido del Sitio',
            },
        ),
    ]
