# Generated by Django 5.2.4 on 2025-10-20 21:24

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_producto_activo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productoimagen",
            options={
                "verbose_name": "Imagen del producto",
                "verbose_name_plural": "Imágenes de productos",
            },
        ),
        migrations.AlterField(
            model_name="productoimagen",
            name="imagen",
            field=models.ImageField(
                help_text="Imagen del producto (se guardará en media/productos/)",
                upload_to=products.models.producto_image_path,
            ),
        ),
    ]
