# Generated by Django 5.2.4 on 2025-11-10 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Reporte')),
                ('tipo', models.CharField(choices=[('ventas', 'Ventas'), ('inventario', 'Inventario'), ('gastos', 'Gastos'), ('nominas', 'Nóminas'), ('general', 'General')], default='general', max_length=20, verbose_name='Tipo de Reporte')),
                ('periodo', models.CharField(choices=[('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('anual', 'Anual'), ('personalizado', 'Personalizado')], default='mensual', max_length=20, verbose_name='Periodo')),
                ('formato', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=10, verbose_name='Formato de Exportación')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha Fin')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='reportes/', verbose_name='Archivo')),
                ('generado', models.BooleanField(default=False, verbose_name='Reporte Generado')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-fecha_creacion'],
                'permissions': [('exportar_reporte', 'Puede exportar reportes'), ('generar_reporte', 'Puede generar reportes automáticamente')],
            },
        ),
    ]
