# Generated by Django 5.2.4 on 2025-11-11 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='datos_json',
            field=models.TextField(blank=True, null=True, verbose_name='Datos del Reporte (JSON)'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='ultima_generacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Generación'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='periodo',
            field=models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('anual', 'Anual'), ('personalizado', 'Personalizado')], default='mensual', max_length=20, verbose_name='Periodo'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='tipo',
            field=models.CharField(choices=[('ventas', 'Ventas'), ('inventario', 'Inventario'), ('gastos', 'Gastos'), ('nominas', 'Nóminas'), ('productos', 'Productos'), ('mesas', 'Mesas y Pedidos'), ('general', 'General')], default='general', max_length=20, verbose_name='Tipo de Reporte'),
        ),
    ]
