# Generated by Django 5.2.4 on 2025-10-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporte',
            options={'ordering': ['-fecha_creacion'], 'permissions': [('exportar_reporte', 'Puede exportar reportes'), ('generar_reporte', 'Puede generar reportes automáticamente')], 'verbose_name': 'Reporte', 'verbose_name_plural': 'Reportes'},
        ),
        migrations.AddField(
            model_name='reporte',
            name='formato',
            field=models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=10, verbose_name='Formato de Exportación'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='generado',
            field=models.BooleanField(default=False, verbose_name='Reporte Generado'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='periodo',
            field=models.CharField(choices=[('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('anual', 'Anual'), ('personalizado', 'Personalizado')], default='mensual', max_length=20, verbose_name='Periodo'),
        ),
    ]
