# Generated by Django 5.2.3 on 2025-07-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_alter_mesa_descripcion_alter_mesa_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('reservada', 'Reservada'), ('fuera de servicio', 'Fuera de servicio')], default='disponible', max_length=20),
        ),
    ]
