# Generated by Django 5.2.3 on 2025-08-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_alter_pedido_mesa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
