# Generated by Django 5.2.3 on 2025-08-25 02:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0006_alter_factura_total_alter_pedidoitem_precio_unitario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='usuarios',
            field=models.ManyToManyField(blank=True, related_name='pedidos_asociados', to=settings.AUTH_USER_MODEL),
        ),
    ]
