# Generated by Django 5.2.4 on 2025-09-10 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_alter_mesa_nombre 2'),
        ('tables', '0007_pedido_usuarios'),
    ]

    operations = [
    ]
